"""Source-faithful Serock P1 act definitions (29 records)."""

from tools.gold_values import observed_state, unclear

MAJER = r"E:\DNA\Helene_Research\Majer_Thirteen_Children.md"
C_SEROCK = r"E:\DNA\Helene_Research\C_Serock_Registers_Goldsztajn_Miara.md"
SCAN = r"E:\DNA\Decode_Package\01_Cyrillic_Serock"
FOND = "73/826/0"


def act(record_id, year, act_type, act_no, source_note, locator, author, facts, artifact=None):
    return {
        "record_id": record_id,
        "town": "Serock",
        "fond": FOND,
        "year": year,
        "act_type": act_type,
        "act_no": act_no,
        "language": "ru",
        "source_note": source_note,
        "source_locator": locator,
        "source_author": author,
        "artifact_path": artifact,
        "facts": facts,
    }


ACT_SPECS = [
    act(
        "serock-1876-marriage-11",
        1876,
        "marriage",
        11,
        C_SEROCK,
        "§1 F1",
        "Agent C",
        {
            "registration_date": {"gregorian": "1876-07-14", "julian": "1876-07-02"},
            "event_date": {"gregorian": "1876-07-13", "julian": "1876-07-01"},
            "principal": {
                "name": "Majer Goldsztejn",
                "age": 19,
                "occupation": "laborer",
                "birthplace": "Serock",
                "residence": unclear("Piskornia", "Liskornia"),
            },
            "father": {"name": "Aron Goldsztejn", "residence": unclear("Piskornia", "Liskornia")},
            "mother": {
                "name": "Jochwet Goldsztejn",
                "residence": unclear("Piskornia", "Liskornia"),
            },
            "spouse": {
                "name": "Ruchla Miara",
                "age": 20,
                "occupation": "worker",
                "birthplace": "Serock",
                "residence": "Serock",
                "marital_status": "maiden",
            },
            "spouse_parents": {
                "father": {"name": "Aron Miara", "marital_status": "deceased"},
                "mother": {
                    "name": "Gitla Miara",
                    "maiden_name": unclear("Kania", "Kanarek"),
                    "residence": "Serock",
                    "marital_status": "widow",
                },
            },
            "witnesses": [
                {
                    "name": "Fajwel Rozenberg",
                    "age": 37,
                    "occupation": "merchant",
                    "residence": "Serock",
                },
                {
                    "name": "Zajwel Rozenberg",
                    "age": 36,
                    "occupation": "merchant",
                    "residence": "Serock",
                },
            ],
            "officiant": "Rabbi Josef Lewinsztejn",
            "rabbi": "Josef Lewinsztejn",
            "banns_dates": [
                "Three announcements in the Serock synagogue; dates not recorded in the "
                "verification note"
            ],
            "prenup_note": "No prenuptial contract",
        },
        rf"{SCAN}\Serock_1876_marriage_acts11-12_Majer_names_Aron_Jochwet_FULLPAGE.jpg",
    ),
    act(
        "serock-1877-birth-25",
        1877,
        "birth",
        25,
        MAJER,
        "§2 children table: Szymsio",
        "Agent C-2",
        {
            "event_date": {"gregorian": "1877-10-23", "julian": "1877-10-11"},
            "principal": {"name": "Szymsio Goldsztejn", "sex": "male", "birthplace": "Serock"},
            "father": {"name": "Majer Goldsztejn", "occupation": "shoemaker"},
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Miara", "age": 18},
            "signatures_note": "Majer Goldsztejn cannot write",
        },
    ),
    act(
        "serock-1882-birth-2",
        1882,
        "birth",
        2,
        MAJER,
        "§2 children table: Icek Moszek",
        "Agent C-2",
        {
            "event_date": "1882-01-23",
            "principal": {"name": "Icek Moszek Goldsztejn", "sex": "male", "birthplace": "Serock"},
            "father": {"name": "Majer Goldsztejn", "occupation": "shoemaker"},
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Miara", "age": 24},
        },
    ),
    act(
        "serock-1883-birth-28",
        1883,
        "birth",
        28,
        MAJER,
        "§3.1 Szaja Berek household",
        "Agent C-2",
        {
            "registration_date": "1883-05-09",
            "event_date": {"year": 1875, "precision": "year"},
            "principal": {"name": "Szajna Sura Goldsztejn", "birthplace": "Piskornia"},
            "father": {
                "name": "Szaja Berek Goldsztejn",
                "occupation": "trader",
                "residence": "Piskornia",
            },
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Krasner", "age": 34},
        },
        rf"{SCAN}\Serock_1883_births_27-30.jpg",
    ),
    act(
        "serock-1883-birth-29",
        1883,
        "birth",
        29,
        MAJER,
        "§3.1 Szaja Berek household",
        "Agent C-2",
        {
            "registration_date": "1883-05-09",
            "event_date": "1877-03-18",
            "principal": {"name": "Jankel Gersz Goldsztejn", "birthplace": "Piskornia"},
            "father": {
                "name": "Szaja Berek Goldsztejn",
                "occupation": "trader",
                "residence": "Piskornia",
            },
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Krasner", "age": 34},
        },
        rf"{SCAN}\Serock_1883_births_27-30.jpg",
    ),
    act(
        "serock-1883-birth-30",
        1883,
        "birth",
        30,
        MAJER,
        "§3.1 Szaja Berek household",
        "Agent C-2",
        {
            "registration_date": "1883-05-09",
            "event_date": {"year": 1879, "month": 3, "precision": "month"},
            "principal": {"name": "Szlama Zelman Goldsztejn", "birthplace": "Piskornia"},
            "father": {
                "name": "Szaja Berek Goldsztejn",
                "occupation": "trader",
                "residence": "Piskornia",
            },
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Krasner", "age": 34},
        },
        rf"{SCAN}\Serock_1883_births_27-30.jpg",
    ),
    act(
        "serock-1884-birth-37",
        1884,
        "birth",
        37,
        MAJER,
        "§3.2 Abram and Minia/Mania Fajga household",
        "Agent C-2",
        {
            "event_date": {"year": 1884, "month": 7, "precision": "month"},
            "principal": {"name": "Icek Moszek Goldsztejn"},
            "father": {
                "name": "Abram Goldsztejn",
                "occupation": unclear("trader", "laborer"),
                "residence": "Serock",
            },
            "mother": {"name": unclear("Minia Fajga", "Mania Fajga"), "maiden_name": "Nowogrod"},
        },
    ),
    act(
        "serock-1884-death-8",
        1884,
        "death",
        8,
        C_SEROCK,
        "§1 F5",
        "Agent C",
        {
            "registration_date": "1884-06-11",
            "event_date": "1884-06-09 22:00",
            "principal": {
                "name": "Aron Goldsztejn",
                "age": 67,
                "occupation": "laborer",
                "birthplace": "Dzierżenin",
                "residence": "Serock",
                "sex": "male",
            },
            "father": {"name": "Szyja"},
            "mother": {"name": "Chawa", "maiden_name": unclear("Jutkowicz?")},
            "declarants": [
                {"name": "Abram Wajngrod", "age": 52},
                {"name": "Zysia Wajngrod", "age": 35},
            ],
            "deceased_left_behind": "wife and children",
        },
        rf"{SCAN}\Serock_1884_death_act8_Aron_Goldsztejn_07-10.jpg",
    ),
    act(
        "serock-1884-death-17",
        1884,
        "death",
        17,
        C_SEROCK,
        "§1 F6 and §3 dead ends",
        "Agent C",
        {
            "event_date": "1884-12-19",
            "principal": {
                "name": "Ruchla Goldsztejn",
                "age": 70,
                "residence": "Cepelin",
                "sex": "female",
                "marital_status": "widow",
            },
            "father": {"name": "Nachman"},
            "mother": {"name": "Itta Laja"},
        },
        rf"{SCAN}\Serock_1884_deaths_15-18.jpg",
    ),
    act(
        "serock-1885-death-1",
        1885,
        "death",
        1,
        MAJER,
        "§2 Icek Moszek fate note",
        "Agent C-2",
        {
            "principal": {
                "name": "Icek Goldsztejn",
                "age": 65,
                "residence": "Cepelin",
                "sex": "male",
            }
        },
        rf"{SCAN}\Serock_1885_deaths_01-02.jpg",
    ),
    act(
        "serock-1885-death-6",
        1885,
        "death",
        6,
        C_SEROCK,
        "§1 F6 and §3 dead ends",
        "Agent C",
        {
            "principal": {
                "name": "Ruchla Goldsztejn",
                "age": 40,
                "birthplace": "Nasielsk",
                "sex": "female",
            },
            "father": {"name": "Jankel"},
            "mother": {"name": "Cyrla"},
            "deceased_left_behind": "husband and children",
        },
        rf"{SCAN}\Serock_1885_deaths_03-06.jpg",
    ),
    act(
        "serock-1888-birth-6",
        1888,
        "birth",
        6,
        MAJER,
        "§3.3 Moszek and Leja Ita household",
        "Agent C-2",
        {
            "event_date": "1888-01-26",
            "principal": {"name": "Dwojra Liba Goldsztejn", "birthplace": "Pokrzywnica"},
            "father": {
                "name": "Moszek Goldsztejn",
                "occupation": "shoemaker",
                "residence": "Pokrzywnica",
            },
            "mother": {"name": "Leja Ita Goldsztejn", "maiden_name": "Cynamon"},
        },
    ),
    act(
        "serock-1888-death-14",
        1888,
        "death",
        14,
        MAJER,
        "§2 children table: Szymsio",
        "Agent C-2",
        {
            "event_date": "1888-02-28",
            "principal": {"name": "Szymsio Goldsztejn", "age": "10 years 5 months", "sex": "male"},
            "father": {"name": "Majer Goldsztejn"},
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Miara"},
        },
        rf"{SCAN}\Serock_1888_deaths_11-14.jpg",
    ),
    act(
        "serock-1888-death-37",
        1888,
        "death",
        37,
        MAJER,
        "§2 children table: Jankel",
        "Agent C-2",
        {
            "event_date": "1888-11-25",
            "principal": {"name": "Jankel Goldsztejn", "age": "2 years 8 months", "sex": "male"},
            "father": {"name": "Majer Goldsztejn"},
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Miara"},
        },
        rf"{SCAN}\Serock_1888_deaths_35-38.jpg",
    ),
    act(
        "serock-1890-birth-1",
        1890,
        "birth",
        1,
        MAJER,
        "§2 children table: Symcha Aron",
        "Agent C-2",
        {
            "event_date": "1889-12-25",
            "principal": {"name": "Symcha Aron Goldsztejn", "birthplace": "Serock", "sex": "male"},
            "father": {"name": "Majer Goldsztejn", "occupation": "trader"},
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Miara", "age": 30},
            "signatures_note": "Majer Goldsztejn signs",
        },
    ),
    act(
        "serock-1890-death-43",
        1890,
        "death",
        43,
        MAJER,
        "§3.2 Abram and Minia/Mania Fajga household",
        "Agent C-2",
        {
            "event_date": "1890-10-08",
            "principal": {
                "name": observed_state("STATED_UNKNOWN"),
                "age": "6 days",
                "sex": "female",
            },
            "father": {"name": "Abram Goldsztejn"},
            "mother": {"name": unclear("Cyrka?")},
        },
        rf"{SCAN}\Serock_1890_deaths_43-46.jpg",
    ),
    act(
        "serock-1891-birth-5",
        1891,
        "birth",
        5,
        MAJER,
        "§3.2 Abram and Minia/Mania Fajga household",
        "Agent C-2",
        {
            "event_date": "1891-01-16",
            "principal": {"name": "Dwojra Goldsztejn"},
            "father": {"name": "Abram Goldsztejn"},
            "mother": {"name": unclear("Minia Fajga", "Mania Fajga"), "maiden_name": "Nowogrod"},
            "signatures_note": "Father signs Goldsztejn in Latin letters",
        },
    ),
    act(
        "serock-1892-birth-12",
        1892,
        "birth",
        12,
        MAJER,
        "§2 children table: Szyja",
        "Agent C-2",
        {
            "event_date": "1892-02-10",
            "principal": {"name": "Szyja Goldsztejn", "birthplace": "Serock", "sex": "male"},
            "father": {"name": "Majer Goldsztejn", "occupation": "trader"},
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Miara", "age": 34},
            "witnesses": [{"name": "Kiwa Kanarek"}],
        },
    ),
    act(
        "serock-1892-death-11",
        1892,
        "death",
        11,
        MAJER,
        "§2 children table: Szyja",
        "Agent C-2",
        {
            "event_date": "1892-04-27",
            "principal": {"name": "Szyja Goldsztejn", "age": "3 months", "sex": "male"},
            "father": {"name": "Majer Goldsztejn"},
            "mother": {"name": "Ruchla Goldsztejn", "maiden_name": "Miara"},
        },
        rf"{SCAN}\Serock_1892_deaths_11-14.jpg",
    ),
    act(
        "serock-1893-marriage-3",
        1893,
        "marriage",
        3,
        MAJER,
        "§3.4 Dawid and Ruchla household",
        "Agent C-2",
        {
            "principal": {"name": "Gerszko Morgensztern", "sex": "male"},
            "father": {"name": "Dawid Morgensztern"},
            "mother": {"name": "Chaja Tauba Morgensztern"},
            "spouse": {"name": "Fajga Goldsztejn", "age": 17, "sex": "female"},
            "spouse_parents": {
                "father": {"name": "Dawid Goldsztejn"},
                "mother": {"name": "Ruchla Goldsztejn", "maiden_name": unclear("Murawczik?")},
            },
        },
        rf"{SCAN}\Serock_1893_marriage_act3_Fajga_Goldsztejn_ELIMINATED_02-03.jpg",
    ),
    act(
        "serock-1894-birth-9",
        1894,
        "birth",
        9,
        MAJER,
        "§3.3 Moszek and Leja Ita household",
        "Agent C-2",
        {
            "event_date": "1894-02-22",
            "principal": {"name": "Szmul Aron Goldsztejn", "birthplace": "Serock", "sex": "male"},
            "father": {"name": "Moszek Goldsztejn", "occupation": "shoemaker"},
            "mother": {"name": "Leja Ita Goldsztejn", "maiden_name": "Cynamon"},
        },
        rf"{SCAN}\Serock_1894_births_09-12.jpg",
    ),
    act(
        "serock-1896-marriage-2",
        1896,
        "marriage",
        2,
        MAJER,
        "§3.5 Abram Josef household",
        "Agent C-2",
        {
            "principal": {
                "name": "Abram Josef Goldsztejn",
                "birthplace": "Nowy Dwór",
                "sex": "male",
            },
            "father": {"name": "Icek Goldsztejn"},
            "mother": {"name": "Rejza Goldsztejn", "maiden_name": unclear("Sem?owska")},
            "spouse": {"name": "Sura Rywka Ziolkowicz", "residence": "Serock", "sex": "female"},
            "spouse_parents": {
                "father": {"name": "Srul Ziolkowicz"},
                "mother": {"name": "Rajca Ziolkowicz"},
            },
        },
        rf"{SCAN}\Serock_1896_marriage_act2_Abram_Goldsztejn_ELIMINATED_02-03.jpg",
    ),
    act(
        "serock-1899-birth-5",
        1899,
        "birth",
        5,
        MAJER,
        "§3.5 Abram Josef household",
        "Agent C-2",
        {
            "event_date": "1898-03-08",
            "principal": {"name": "Chaja Goldsztejn", "sex": "female"},
            "father": {"name": "Abram Josef Goldsztejn"},
            "mother": {"name": "Sura Rywka Goldsztejn", "maiden_name": "Ziolkowicz"},
        },
    ),
    act(
        "serock-1899-birth-6",
        1899,
        "birth",
        6,
        MAJER,
        "§3.5 Abram Josef household",
        "Agent C-2",
        {
            "event_date": {"gregorian": "1899-02-11", "julian": "1899-01-30"},
            "principal": {"name": "Szlama Majer Goldsztejn", "sex": "male"},
            "father": {"name": "Abram Josef Goldsztejn"},
            "mother": {"name": "Sura Rywka Goldsztejn", "maiden_name": "Ziolkowicz"},
        },
    ),
    act(
        "serock-1902-marriage-3",
        1902,
        "marriage",
        3,
        MAJER,
        "§3.6 Gerszon namesake trap",
        "Agent C-2",
        {
            "principal": {
                "name": "Gerszon Goldsztejn",
                "age": 25,
                "birthplace": "Nasielsk",
                "residence": "Nasielsk",
                "sex": "male",
            },
            "father": {"name": "Majer Goldsztejn"},
            "mother": {"name": "Rywa Goldsztejn", "maiden_name": "Owsianka"},
            "spouse": {"name": "Rojza Kolender", "age": 20, "residence": "Serock", "sex": "female"},
            "spouse_parents": {
                "father": {"name": "Chaim Kolender"},
                "mother": {"name": "Chinda Ruchla Kolender", "maiden_name": "Lisman"},
            },
            "banns_dates": ["Banns in Serock synagogue", "Banns in Nasielsk synagogue"],
        },
    ),
    act(
        "serock-1902-death-25",
        1902,
        "death",
        25,
        MAJER,
        "§1 Ruchla double registration",
        "Agent C-2",
        {
            "registration_date": "1902-11-06",
            "event_date": "1902-11-05 05:00",
            "principal": {
                "name": "Ruchla Goldsztejn",
                "maiden_name": "Miara",
                "age": 42,
                "sex": "female",
            },
            "father": {"name": "Aron Miara"},
            "mother": {"name": "Gitla Miara", "maiden_name": "Kanarek"},
            "declarants": [
                {"name": "Lejzor Wielkobroda", "age": 46},
                {"name": "Chaim Wielkobroda", "age": 25},
            ],
            "deceased_left_behind": "husband Majer Goldsztejn",
        },
    ),
    act(
        "serock-1903-death-5",
        1903,
        "death",
        5,
        C_SEROCK,
        "§1 F3",
        "Agent C",
        {
            "registration_date": "1903-03-10",
            "event_date": "1903-03-09 05:00",
            "principal": {
                "name": "Gitla Miara",
                "age": 78,
                "residence": "Serock",
                "sex": "female",
                "marital_status": "widow",
            },
            "father": {"name": "Mordka Kanarek"},
            "mother": {"name": "Bejla Kanarek"},
        },
        rf"{SCAN}\Serock_1903_deaths_03-06.jpg",
    ),
    act(
        "serock-1903-death-6",
        1903,
        "death",
        6,
        C_SEROCK,
        "§1 F2",
        "Agent C",
        {
            "registration_date": "1903-04-11",
            "event_date": "1903-04-10 01:00",
            "principal": {
                "name": "Ruchla Goldsztejn",
                "maiden_name": "Miara",
                "age": 42,
                "sex": "female",
            },
            "father": {"name": "Aron Miara"},
            "mother": {"name": "Gitla Miara", "maiden_name": "Kanarek"},
            "declarants": [
                {"name": "Lejzor Wielkobroda", "age": 47, "occupation": "szkolnik"},
                {"name": "Chaim Wielkobroda", "age": 26, "occupation": "bookbinder"},
            ],
            "deceased_left_behind": "husband Majer Goldsztejn",
        },
        rf"{SCAN}\Serock_1903_deaths_03-06.jpg",
    ),
    act(
        "serock-1903-marriage-23",
        1903,
        "marriage",
        23,
        C_SEROCK,
        "§1 F8 bonus act",
        "Agent C",
        {
            "registration_date": "1903-12-12",
            "principal": {"name": "Zacharia Berek Kuligowski", "age": 19, "sex": "male"},
            "father": {"name": "Jankel Kuligowski"},
            "mother": {"name": "Bajla Perla Kuligowski", "maiden_name": "Borensztejn"},
            "spouse": {"name": "Szajna Dwojra Wajngrod", "age": 18, "sex": "female"},
            "spouse_parents": {
                "father": {"name": "Zysia Wajngrod", "marital_status": "deceased"},
                "mother": {"name": "Rejza Wajngrod", "maiden_name": "Mielnik"},
            },
        },
    ),
]
